Webhook subscriptions extension
mirumee/saleor-app-framework-python pull request #45
Opened 2022-09-28 09:27 UTC by piotrjmm

2022-09-28 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-app-framework-python?pullRequest=45) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-app-framework-python?pullRequest=45) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-app-framework-python?pullRequest=45) it.</sub>

2022-09-28 09:50 UTC, rafalp requested changes

2022-09-28 09:50 UTC, rafalp commented on src/saleor_app/endpoints.py
> +                (
Shouldn't we iterate on `http_routes` instead of `http_routes.items()` and remove `, _` from forloop if we are not using dict item's value here?

2022-09-28 09:50 UTC, rafalp commented on src/saleor_app/install.py
> +    events: Dict[str, tuple[SaleorEventType, str]],
using `tuple` instead of `Tuple` from typing will raise Python version requirement.

2022-09-28 09:50 UTC, rafalp commented on src/saleor_app/webhook.py
> +        self.http_routes_subscriptions = {}
Can we switch 43 and 44 with places?

2022-09-28 09:50 UTC, rafalp commented on src/saleor_app/webhook.py
> +            if subscription_query:
```suggestion

            if subscription_query:
```

2022-10-05 08:04 UTC, pkucmus approved these changes

2022-10-05 09:29 UTC, rafalp commented
@piotrjmm build is currently failing for this

2022-10-05 13:21 UTC, rafalp approved these changes

2022-10-05 15:33 UTC, merged